title: Documentation
doc_version: 1.2.1
url: https://random-ball-cover.nlamprian.me

permalink: /:categories/:title
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
  - jemoji
  - rouge
